- .gitignore
- doc/Makefile
- doc/make.bat
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.gitignore
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/doc/Makefile
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/doc/make.bat
- Clean target consistency for bat and Makefile, remove _autosummary areas.
- Added `-j auto` used by pymapdl and pyfluent
- Changed the recommended build directory name from `build` to `_build` so it's consistent with .gitignore
> Tidy up clean targets, add -j auto Sphinx option

- .github/workflows/ci.yml
Allows the release job to get access to the distribution files.
> Use artifacts in CI

- pyproject.toml
Given the [issue within cookiecutter's release](https://github.com/cookiecutter/cookiecutter/issues/1636), I've gone ahead and released a renamed, but otherwise identical, `ansys-cookiecutter` package at https://pypi.org/project/ansys-cookiecutter/.
This is by no means a permanent solution, and since the github repo has 16.5k stars, I'm sure that someone will come up with a workaround, fork, or will just post the package. For now, we're using this to get the job done and will take it down once 2.X is released.
Installation of this package is:
```
pip install ansys-cookiecutter
```
and it will show up from `pip list` as `ansys-cookiecutter`, but otherwise it's identical to the actual package. For example both:
```
python -m cookiecutter
```
```
python -c "import cookiecutter"
```
work …
> Update pyproject.toml to use ansys-cookiecutter

- README.rst
- doc/source/getting_started/index.rst
- doc/source/user_guide/index.rst
- doc/source/user_guide/templating.rst
- doc/source/user_guide/usage.rst
Kelly Fletcher tried to use this doc to set up a PyAnsys project for NSV doc and had problems because ansys-templates was noted instead of pyansys-templates. She also couldn't use pipx. I'll add a comment in the file to better explain.
> ansys-templates edits to doc

- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml
Some of the steps names in the generated CI/CD do not match well what they are actually doing
> Minor improvements to steps names

- src/ansys/templates/python/pyansys/cookiecutter.json
- src/ansys/templates/python/pyansys/{{cookiecutter.__project_name_slug}}/setup.py
- src/ansys/templates/python/pyansys_advanced/cookiecutter.json
- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/pyproject_flit.toml
- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/pyproject_poetry.toml
- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/setup_setuptools.py
- src/ansys/templates/python/pybasic/cookiecutter.json
- src/ansys/templates/python/pybasic/{{cookiecutter.__project_name_slug}}/setup.py
Resolves #42 by adding the required metadata. Small enhancements to private variables have been made too.
The order in the `setup.py` files is the one specified in the [declarative configuration](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#declarative-config) from the Setuptools guidelines.
> Fix Python templates metadata

- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
Documentation: add breadcrumbs.
This adds the line "PyAnsys >> MyPackage >> Current Page" in the header, as seen in [pymapdldoc](https://mapdldocs.pyansys.com/getting_started/index.htmlhttps://mapdldocs.pyansys.com/getting_started/index.html) and others
Note: I'm not familiar enough with the stack to verify this change locally, I only applied the same in an already existing repo
> Add breadcrumbs

- .coveragerc
- .pre-commit-config.yaml
- pyproject.toml
- src/ansys/templates/python/pyansys_advanced/hooks/post_gen_project.py
- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/.pre-commit-config.yaml
- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/pyproject.toml
Partially solves for #50.
* **Migrated tools:** black, isort, coverage and pydocstyle
* **Lacking of PEP 518 support:** flake8, codespell
> Move style tools config to pyproject.toml

- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/pyproject.toml
Fixes a bug I introduced in #53. The "pydocstyle" tool has no "exclude" flag. Also, it ignores tests by default.
> Fix pydocstyle config pyansys-advanced

- .github/workflows/ci.yml
Enables coverage report upload to [Codecov], as it happens with other public PyAnsys projects.
[Codecov]: https://app.codecov.io/
> Enable codecov upload

- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
The grpc python documentation can be used to generated links when exposing grpc objects. Given how widely we are using it, I think it's worth adding it to the suggested intersphinx_mapping list
> Suggest grpc intersphinx

- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/tox.ini
- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/README.rst
- tox.ini
When reviewing PyPIM docs, @PipKat was wondering if it was worth it to document how to find your python version to be able to run "tox -e py3X". It turns out that by default, tox provides an environment named "py" picking the current python version: https://tox.wiki/en/latest/config.html#tox-environments
This PR adds the same unversioned "py", and uses it in the `README`, under the assumption that by default, a developer just want to run the test with the current python version. The only variation from the default tox behavior is the selection of "python3" to avoid a fallback on python2 on some linux distrib.
> Add a non-versionned python tox environment

- pyproject.toml
- requirements/requirements_dev.txt
`cookiecutter==2.1.0` is finally released see [pypi cookiecutter==2.1.0](https://pypi.org/project/cookiecutter/2.1.0/).
This PR updates the requirements accordingly.
> Use official cookiecutter

- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml
As commented, force cookiecutter to implement the MAIN_PYTHON_VERSION variable so that mods only take place in one line,instead of in all `python-version` lines.
> Use MAIN_PYTHON_VERSION env var

- requirements/requirements_build.txt
- requirements/requirements_doc.txt
- requirements/requirements_tests.txt
- src/ansys/templates/python/common/cookiecutter.json
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/dependabot.yml
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/requirements_build.txt
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/requirements_doc.txt
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/requirements_tests.txt
- src/ansys/templates/python/pyace_fastapi/cookiecutter.json
- src/ansys/templates/python/pyace_fastapi/hooks/post_gen_project.py
- src/ansys/templates/python/pyace_flask/cookiecutter.json
- src/ansys/templates/python/pyace_flask/hooks/post_gen_project.py
- src/ansys/templates/python/pyace_grpc/cookiecutter.json
- src/ansys/templates/python/pyace_grpc/hooks/post_gen_project.py
- src/ansys/templates/python/pyace_pkg/cookiecutter.json
- src/ansys/templates/python/pyace_pkg/hooks/post_gen_project.py
- src/ansys/templates/python/pyansys/cookiecutter.json
- src/ansys/templates/python/pyansys_advanced/cookiecutter.json
- src/ansys/templates/python/pyansys_advanced/hooks/post_gen_project.py
- src/ansys/templates/python/pyansys_openapi_client/cookiecutter.json
- src/ansys/templates/python/pybasic/cookiecutter.json
- tests/tests_templates/test_python_templates.py
Fixing requirements is the best way for making sure dependabot opens keeps requirements up to date.
Also, this PR implements this bot in the modern templates.
> Fix requirements and include dependabot

- pyproject.toml
Just noticed this outdated section in the `pyproject.toml` file. From [flit docs](https://flit.pypa.io/en/latest/pyproject_toml.html#sdist-section):
> When you use [flit build](https://flit.pypa.io/en/latest/cmdline.html#build-cmd) or [flit publish](https://flit.pypa.io/en/latest/cmdline.html#publish-cmd), Flit builds an sdist (source distribution) tarball containing the files that are checked into version control (git or mercurial).
Checked locally and all required files are being included in the sdist.
> Remove outdated flit sdist section

- .github/labels.yml
Adding a new label to identify which issues or PR are blocked due to other pending tasks.
> Add blocked label

- README.rst
Fix #139 by updating the documentation link to the new domain.
> FIX: doc link in README.rst

- .pre-commit-config.yaml
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.pre-commit-config.yaml
In the pre-commit configuration for flake8, refer to the 'main' repository on GitHub, instead of its GitLab mirror.
Update the flake8 version to '5.0.4'.
Using the gitlab mirror caused 'pre-commit autoupdate' to not pick up new versions (at least in my project, didn't try to consistently reproduce this).
> Consume flake8 from github instead of gitlab mirror

- pyproject.toml
Downgrades the Sphinx version to version 5.3.0 to avoid missing icons in the top navigation bar.
> MAINT: downgrade sphinx to 5.3.0

- .pre-commit-config.yaml
- .reuse/dep5
- .reuse/templates/ansys.jinja2
- COPYING
- LICENSES/MIT.txt
- README.rst
- doc/source/conf.py
- doc/source/getting_started/index.rst
- doc/source/index.rst
- doc/source/templates.rst
- doc/source/user_guide/index.rst
- doc/source/user_guide/templating.rst
- doc/source/user_guide/usage.rst
- pyproject.toml
- src/ansys/templates/__init__.py
- src/ansys/templates/__main__.py
- src/ansys/templates/cli.py
- src/ansys/templates/paths.py
- src/ansys/templates/testing.py
- src/ansys/templates/utils.py
- tests/test_cli.py
- tests/test_testing.py
- tests/tests_templates/test_python_templates.py
Partially solves for #209 by adding reuse-tool in pre-commit.
For some of the files, the license is specified using [the dep5 file](https://github.com/ansys/ansys-templates/pull/210/files#diff-1c645862be9de205dccc305cde10248abfe5b5a2297fc0502cbdd22cae5c9305).
> MAINT: implement reuse-tool for checking heading licenses

- doc/source/conf.py
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
- src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
As title says. We should point towards the latest stable version of the Python docs
> fix: intersphinx mapping for Python docs

- src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/compose.yaml
The tracelens image used by compose.yaml is currently broken. This is now using a tracelens image hosted on fuji environment.
> Fix broken tracelens image on compose.yaml

- .github/workflows/ci.yml
- pyproject.toml
This pull-request limits the version of cookiecutter for solving the latest CI/CD issues.
> fix: limit upper version of cookiecutter

- src/ansys/templates/python/osl_solution/hooks/post_gen_project.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/poetry.lock
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/pyproject.toml
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/definition.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/monitoring_step.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/actor_information_table.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/actor_logs_table.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/actor_statistics_table.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/design_table.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/node_control.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/project_information_table.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/service_table.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/system_files.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/monitoring_page.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/problem_setup_page.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/design_table_view.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/project_summary_view.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/result_files_view.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/scenery_view.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/status_overview_view.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/summary_view.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/visualization_view.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/utilities/common_functions.py
- tests/tests_templates/test_python_templates.py
> [REFACTORING] General refactoring of the osl-template

- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py
- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/problem_setup_page.py
The workaround implemented to resolve this [issue ](https://github.com/Solution-Applications/solution-enablement-product-management/issues/546) is not working - see reported bug [here](https://github.com/orgs/Solution-Applications/saml/initiate?return_to=https%3A%2F%2Fgithub.com%2FSolution-Applications%2Fsolution-enablement-product-management%2Fissues%2F617). The issue is that we have one transaction method that is triggered every time theres a change in the UI - this is done to update a step field to persist data in the ui. If this method is triggered too quickly (under1-4 sec), a conflict error is raised saying this method is already running. The workaround was to get the state of the method and force it to complete before re-triggering the method. However, this does not appear to work. …
> Prevent ConflictError that occurs when updating UI placeholder values too quickly

- src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
- src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
Pass empty string to `github_url` if repository key is not defined in the `tool.poetry` section of the `pyproject.toml`.
> fix: handle missing repository key in pyproject.toml.

- src/ansys/templates/python/pyansys/{{cookiecutter.__project_name_slug}}/README.rst
- src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/README.rst
- src/ansys/templates/python/pybasic/{{cookiecutter.__project_name_slug}}/README.rst
The open command will use the default system browser to open the file https://linux.die.net/man/1/open
> tweak: use open instead of your_browser_name

- .github/workflows/solutions_ci.yml
In this PR, I  adjusted the workflow to trigger the e2e tests.
We check if there is a change in `src/ansys/templates/python/solution/`.
When there is a change, the e2e tests are triggered and the following status is sent by the external workflow.
When there is no change, we mock the status as below.
This will allow to make the e2e tests required to merge the pull requests.
> ci: make the e2e tests required

- doc/changelog.d/480.fixed.md
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml
Without that line all tests would run with python 3.10, no matter what's in the version matrix.
We noticed because we broke support for python 3.9 without the CI warning us.
Before, it's happy: https://github.com/ansys/pysimai/actions/runs/8881939762
After, it catches the issue: https://github.com/ansys/pysimai/actions/runs/9159532632
> fix: run tests with specified python-version in CI

- doc/changelog.d/478.fixed.md
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/pyproject.toml
> fix: update pydocstyle in ``pyproject.toml`` file

- doc/changelog.d/485.fixed.md
- src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/CODE_OF_CONDUCT.md
Codespell fails the "code style" job in v2.3.0 due to "socio-economic" in the CODE_OF_CONDUCT.md file. This PR changes the spelling to socioeconomic
Code style failure due to "socio-economic": https://github.com/ansys/pymechanical-embedding-examples/actions/runs/9260367397/job/25474002779
PR: https://github.com/ansys/pymechanical-embedding-examples/pull/198/files
> fix: change socio-economic to socioeconomic for codespell v2.3.0

- doc/changelog.d/487.fixed.md
- doc/source/changelog.rst
- doc/source/conf.py
- doc/source/templates.rst
- pyproject.toml
The docs build  was failing because of the autosectionlabel was on and there will be duplicated label in case of changelog. So supressing the autosection label warning
https://github.com/ansys/ansys-templates/actions/runs/9362587943/job/25771639895#step:2:975
.
> fix: suppress ``autosectionlabel`` warning for ``changelog`` file

- doc/changelog.d/495.fixed.md
- src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/setup_environment.py
It is considered as a good practice that whenever you change the `pyproject.toml` file, you should run `poetry lock --no-update` afterwards to sync the `poetry.lock` files with those changes. This is what we do when some packages are provided as wheel files through the `setup_environment.py`. The `--no-update` flag tries to preserve existing versions of dependencies. 
In this PR I am executing `poetry lock --no-update` as part of `setup_environment.py` before installing dependencies.
> fix: updating poetry.lock before local wheels are used in solution template

- README.md
The link in the demo/solution branch to get the latest PYPI PAT is obsolete. 
This PR aims to replace it with the correct one.
> Fix PYPI PAT
