ansys/ansys-templates

src/ansys/templates/cli.py
tests/test_cli.py

Fix pyansys-advanced name in list command

---

doc/source/user_guide/usage.rst

Fix pipx command

---

doc/source/getting_started/index.rst

This PR fixes some typos, links, command and adds an upgrade guideline. These are the last changes before releasing 0.1.0.

Fix minor bugs and typos in docs

---

doc/source/getting_started/index.rst

Fix doc commands

---

src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/requirements_tests.txt
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml

Fix Python templates actions

---

src/ansys/templates/python/common/cookiecutter.json
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.coveragerc
src/ansys/templates/python/pyansys/cookiecutter.json
src/ansys/templates/python/pyansys_advanced/cookiecutter.json
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/tox.ini
src/ansys/templates/python/pybasic/cookiecutter.json
tests/tests_templates_python/conftest.py

Implement code coverage across Python templates

---

.github/workflows/templates_python.yml
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/.pre-commit-config.yaml
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/tox.ini

Resolves #4. Really need to have this implemented.

Test baked actions

---

src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml
tests/tests_templates/test_python_templates.py

Move GitHub actions to common/ dir

---

doc/source/getting_started/index.rst

Fix installation commnad

---

src/ansys/templates/testing.py
src/ansys/templates/utils.py

Continues the work from #70 by fixing the paths flavors according to the baking OS to ensure desired project structure.

Fix paths flavours

---

README.rst
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/README.rst

Resolves #54 by including the following badges:
<div align="center">
</div>

Include badges in project and pyansys-advanced

---

.github/workflows/ci.yml
.github/workflows/templates_python.yml
README.rst

Deploy baked template demos in branches

---

.github/workflows/templates_python.yml

Allows to manually execute workflows.

Enable workflow dispatch

---

src/ansys/templates/python/pyansys/{{cookiecutter.__project_name_slug}}/README.rst
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/README.rst
src/ansys/templates/python/pybasic/{{cookiecutter.__project_name_slug}}/README.rst

Fix venv activation instructions

---

doc/source/user_guide/usage.rst

Hotfix to include recently migrated templates in the user guide.

Fix doc to include ACE templates

---

src/ansys/templates/__main__.py

Allow executing ansys-templates as Python module

---

.github/workflows/ci.yml
.github/workflows/label.yml
.github/workflows/templates_python.yml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/label.yml

Disable CI when concurrent workflows ongoing

---

.github/workflows/label.yml
README.rst
doc/source/templates.rst

Related with https://github.com/ansys/ansys-templates/issues/115.

Update links to ansys/ansys-templates

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

Adding issue templates

---

doc/source/conf.py

Using Ansys logo instead of PyAnsys one

---

.gitignore
README.rst
pyproject.toml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.gitignore
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/tox.ini
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/README.rst
tox.ini

Minor improvements to coverage output and badges

---

src/ansys/templates/python/pyansys/{{cookiecutter.__project_name_slug}}/README.rst
src/ansys/templates/python/pyansys_advanced/{{cookiecutter.__project_name_slug}}/README.rst
src/ansys/templates/python/pybasic/{{cookiecutter.__project_name_slug}}/README.rst

Fixing readme's format

---

doc/Makefile
doc/make.bat

Now that [pyansys/actions] includes a [PDF building step], we need to implement it in this project.
[pyansys/actions]: https://github.com/pyansys/actions
[PDF building step]: https://github.com/pyansys/actions/blob/f3262811fd4ed12f79fa2fc019509e5b041eaee2/doc-build/action.yml#L84-L90

FEAT: implement PDF biulder

---

doc/source/conf.py

Add theme switcher and github logo at nav end.

change version switcher position

---

doc/source/conf.py

Creating a favicon is a small but important step to setting docs, it adds legitimacy to docs.

Add favicon and title

---

doc/source/conf.py

Ensure only major and minor numbers are written in the documentation.

FIX: versoin in release mapper config

---

.github/workflows/templates_python.yml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/dependabot.yml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/pyproject.toml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/tox.ini
src/ansys/templates/python/pyansys_advanced/hooks/post_gen_project.py
tests/tests_templates/test_python_templates.py

This pull request solves all issues related with poetry-based pyansys-advanced template:

Fix poetry-based pyansys-advanced template

---

pyproject.toml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/pyproject.toml

FEAT: add project urls

---

src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml

Fix #207 by indicating when to execute this job.

FIX: CI/CD job execution

---

.pre-commit-config.yaml

This pull-request updates various pre-commit hooks. Let us consider adding this to the set of repositories using the `pre-commit` action.

MAINT: update pre-commit hooks

---

.github/workflows/ci.yml
.github/workflows/templates_python.yml
tox.ini

Minimum Python from 3.7 to 3.8

Bump CI and tox to 3.8

---

.github/workflows/ci.yml
.pre-commit-config.yaml
doc/source/_templates/sidebar-nav-bs.html

Fixes the issues found in https://github.com/ansys/ansys-templates/actions/runs/4479592225

FIX: ci/cd syntax

---

src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/.github/workflows/ci.yml
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/pyproject.toml
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/setup_environment.py

https://github.com/Solution-Applications/solution-developers-support-center/issues/210
Upgrade poetry to 1.5 in Cookie-cutter

Upgrade the version of Poetry to 1.5.1

---

src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml
src/ansys/templates/python/common/{{cookiecutter.__project_name_slug}}/requirements_doc.txt

Rename the pyansys/actions to ansys/actions in templates.

FIX: Rename the pyansys/actions to ansys/actions in templates.

---

pyproject.toml
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/.env
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/pyproject.toml

In this PR, I adjusted the templates for the SAF solution so that it works with the portal 0.2.1 and glow 0.3.dev4.

Adjusting templates for SAF solution so that it works with portal 0.2.1 and glow 0.3.dev4

---

pyproject.toml

As per some internal discussion and considering the maturity of this project, the next release will be 1.0.0.

MAINT: bump 1.0.dev0

---

src/ansys/templates/python/osl_solution/cookiecutter.json
src/ansys/templates/python/solution/cookiecutter.json

The aim of this pull request is simply to authorize spaces in project name and solution name.

Enabling space in project name and solution name.

---

src/ansys/templates/python/solution/hooks/post_gen_project.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/poetry.lock
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/pyproject.toml
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/first_page.py
tests/tests_templates/test_python_templates.py

- Add workflow image in ui/assets/images
- Integrate ansys-solutions-dash-lib
- Updated lock file

Add missing asset in UI + Integrate solutions Dash lib

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/poetry.lock
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/pyproject.toml
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/problem_setup_page.py

This PR includes:
- pattern matching callbacks that use the oSL component ids from the ansys-solutions-optislang-frontend-components package to retrieve ui placeholder values
- updates to the problem_setup_step module to include two transaction methods to 1. update the placeholders for data persistence and 2. write the new properties file for analysis

Update problem setup step in oSL solution template to use latest oSL packages to update placeholder values with ui placeholders

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/pyproject.toml
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/pyproject.toml

Update the solution portal recommended version

update solution template - updgrade portal recommended version to 0.4.1

---

src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/first_page.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py

As explained in GLOW's documentation: https://saf.docs.solutions.ansys.com/version/dev/user_guide/debug.html#creating-and-accessing-dash-ui-callback-execution-logs, solutions should use GLOW's callback instead of the one from Dash to have logging and tracing enabled.

Use GLOW's callback in solution template

---

src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/.github/workflows/ci.yml

Fix the syntax errors of the `ci.yml` file for the Solution template.

Fix solution CI workflow syntax

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/actor_information_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/actor_logs_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/actor_statistics_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/commands.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/design_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/logs_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/project_information_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/service_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/system_files.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/utils/common_functions.py

Implement a pie chart for actors of type system in the actor information component.

[FEAT] Add pie chart to the information table of system-like actors.

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py

This pull request add a button on the UI to enable the user to switch to webrowser view and continue with a new project creation.

[FEAT] Add browser view button.

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/commands.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/monitoring_page.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/problem_setup_page.py

This pull request brings the following changes on the optiSLang solution template:
- Add progress bar at solution initialization
- Get TCP address using `osl.get_osl_server().get_host()`
- Refactor problem_setup page

[FEAT] Add progress bar at solution initialization

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/problem_setup_page.py

This PR removes infinite loop that was included by mistake.

Remove infinite loop from problem_setup_page

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/monitoring_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/monitoring_page.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py

Fix optiSLang logs button and add select view dropdown

---

src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/pyproject.toml

The previous versions of glow and portal are not compatible and this combination is working

updating versions of glow and portal

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/pim_configurations/osl_wrapper.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/monitoring_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/optislang_manager.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/monitoring_page.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/design_table_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/project_summary_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/scenery_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/status_overview_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/summary_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/visualization_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/utilities/common_functions.py

Adjust update_project_data transaction to handle nan values from osl

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/poetry.lock
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/pyproject.toml
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/problem_setup_page.py

This PR includes the following changes to the osl-solution template:
- pyproject.toml with latest release of optislang-frontend-components 
- replaced faulty logic used in initializing and updating placeholders of bool type
- Fixes problem seen in: https://github.com/orgs/Solution-Applications/projects/47/views/1?pane=issue&itemId=38034953
1. Checkout branch associated to this PR
2. In a .venv run: flit install to gather latest changes made to the osl-solution template
3. Create a new osl-solution using overview_project.owa: ansys-templates new solution -f owa -a <path-to-owa-file>
4. In your terminal, set your current directory to the directory of the new solution.
5.  Setup the python virtual environment by running: python setup_environment.py -d run
6.  Run the solution and create a …

fix bug 620

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py

The OSL timeout seems to be too low for some users. In this PR the timeout is increased as well as the maximum number of attempts.

Increase OSL server timeout and max number of attempts.

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/problem_setup_page.py

This PR fixes bug: https://github.com/Solution-Applications/solution-enablement-product-management/issues/691

fix bug 921927

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/monitoring_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/components/actor_logs_table.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/summary_view.py

The PR contains the following changes:
* Persisting the page number for the pagination in actor logs table
* Fix for problem setup page not showing after initialization

Persist pagination for datatable 

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/.github/workflows/ci.yml

Add missing closing brackets in ci.yml file for osl-solution template."

Add missing brackets in ci.yml file.

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/monitoring_step.py

This PR contains the following changes:
* Update in the method "control_node_state" to implement shutdown

Update node control method for shutdown

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/design_table_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/project_summary_view.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/summary_view.py

The PR includes:
* Inclusion of try block for Json decode error within callbacks

Update callbacks for json decode error

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/datamodel/datamodel.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/problem_setup_step.py
src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/summary_view.py

1. the total number of designs displayed, is obtained from the total number of designs already scheduled (i.e. total number of designs in the design table). However, this is not the total number of designs that are expected to be generated. optiSLang algorithms (Sensi, DOE, Optimization, ...) generate/schedule designs in iterations.
2. The expected total number of designs is now obtained by getting and inspecting the [actor_info] of a certain system.

Total designs value now extracted from actor_info

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py

This PR fixes bug logged here: https://github.com/Solution-Applications/solution-enablement-product-management/issues/738

Fixes bug thrown on page load of oSL solution

---

.gitignore
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/doc/source/conf.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/setup_environment.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/main.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/definition.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/app.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/first_page.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/intro_page.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py

Prevent a newly created solution from failing the [code style check](https://github.com/Solution-Applications/actions/tree/main/check-code-style).

Fix SAF Solution code style

---

src/ansys/templates/python/osl_solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/views/summary_view.py

The PR contains the fix for the issue identified in : https://github.com/Solution-Applications/solution-enablement-product-management/issues/626

Issue 626: Fetch solution name from template

---

src/ansys/templates/python/doc_project/{{cookiecutter.__project_name_slug}}/.github/workflows/ci_cd.yml
src/ansys/templates/python/doc_project/{{cookiecutter.__project_name_slug}}/.pre-commit-config.yaml

Fix :  precommit hook for doc project

---

src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/setup_environment.py

solutions-common-files repository is now archived and setup_environment.py is versioned via ansys-templates only.

Update setup script from solutions-common-files d983a4c.

---

src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/README.rst
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/poetry.lock
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/pyproject.toml
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/solution/definition.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/first_page.py
src/ansys/templates/python/solution/{{cookiecutter.__project_name_slug}}/src/ansys/solutions/{{cookiecutter.__solution_name_slug}}/ui/pages/page.py

Replace AWC Tree by Dash Tree in the default UI mode of the solution template

Replace AWC Tree by Dash Tree in the default UI mode of the solution template

---

CONTRIBUTING.md
CONTRIBUTORS.md
doc/changelog.d/509.fixed.md

fix: contribut**** files

---

.gitattributes
doc/changelog.d/536.maintenance.md
doc/changelog.d/changelog_template.jinja
pyproject.toml

Add .gitattributes file to the repository

feat: Add .gitattributes file
